### ISSUE TITLE
Пример конфигурационного файла

### ISSUE THREAD

**Issue by markpolyak** [markpolyak/lab-grader-new#7]
```yaml
---
# Configuration file for lab-grader

course:
    name: Operating systems
    alt-names: 
        - OS
        - Операционные системы
        - ОС
    semester: Spring 2024
    email: k43guap@ya.ru
    timezone: UTC+3
    github:
        organization: suai-os-2024
        teachers:
            - "Mark Polyak"
            - markpolyak
    google:
        spreadsheet: 1xmnbiOoer4wFUozDRya1WLz_mDIXF2oOEamnKU31EnQ
        info-sheet: График
        task-id-column: 0
        student-name-column: 1
        lab-column-offset: 1
    staff:
        - name: Поляк Марк Дмитриевич
          title: ст. преп.
          status: лектор
        - name: Поляк Марк Дмитриевич
          title: ст. преп.
          status: лабораторные работы
    labs:
        "0":
            github-prefix: os-task0
            short-name: ЛР0
            penalty-max: 5
            ignore-task-id: True
            ci:
                - workflows
            files:
                - goals.md
                - info.md
                - report.pdf
            moss:
                language: c
            report:
                - Задание
                - Результат
        "01":
            github-prefix: os-task-I-1
            short-name: ЛР0.1
            taskid-max: 20
            penalty-max: 6
            # ignore-task-id: True
            ci:
                - workflows
            files:
                - typescript
            moss:
                language: c
                max-matches: 1000
            report:
                - Цель работы
                - Индивидуальное задание
                - Результат выполнения работы
                - Содержимое файла typescript c записанной последовательностью команд
                - Выводы
        "1":
            github-prefix: os-task1
            short-name: ЛР1
            taskid-max: 25
            penalty-max: 6
            ci:
                - workflows
            files:
                - lab1.sh
            moss:
                language: c
                max-matches: 1000
                local-path: lab1
                additional:
                  - suai-os-2020
                  - suai-os-2021
                  - suai-os-2022
                  - suai-os-2023
                basefiles:
                    - 
                        repo: k43guap/os-course-task1
                        filename: lab1.sh
            report:
                - Цель работы
                - Индивидуальное задание
                - Описание входных данных
                - Результат выполнения работы
                - Исходный код программы с комментариями
                - Выводы
        "2":
            github-prefix: os-task2
            short-name: ЛР2
            taskid-max: 20
            taskid-shift: 4
            penalty-max: 9
            ci:
                - workflows
            files:
                - lab2.cpp
            moss:
                language: cc
                max-matches: 1000
                local-path: lab2
                additional:
                  - suai-os-2020
                  - suai-os-2021
                  - suai-os-2022
                  - suai-os-2023
                basefiles:
                    - 
                        repo: k43guap/os-course-task2
                        filename: lab2.cpp
                    - 
                        repo: k43guap/os-course-task2
                        filename: examples/ex3.cpp
            report:
                - Цель работы
                - Задание на лабораторную работу
                - Граф запуска потоков
                - Результат выполнения работы
                - Исходный код программы с комментариями
                - Выводы
        "3":
            github-prefix: os-task3
            short-name: ЛР3
            taskid-max: 20
            penalty-max: 7
            ci:
                - workflows
            files:
                - lab3.cpp
            moss:
                language: cc
                max-matches: 1000
                local-path: lab3
                additional:
                  - suai-os-2020
                  - suai-os-2021
                  - suai-os-2022
                  - suai-os-2023
                basefiles:
                    - 
                        repo: k43guap/os-course-task3
                        filename: lab3.cpp
            report:
                - Цель работы
                - Задание на лабораторную работу
                - Граф запуска потоков
                - Результат выполнения работы
                - Исходный код программы с комментариями
                - Выводы
        "4":
            github-prefix: os-task4
            short-name: ЛР4
            taskid-max: 30
            penalty-max: 8
            ci:
                - workflows
            files:
                - lab4.cpp
            moss:
                language: cc
                max-matches: 100
                local-path: lab4
                additional:
                  - suai-os-2021
                  - suai-os-2022
                  - suai-os-2023
                basefiles:
                    - 
                        repo: k43guap/os-course-task4
                        filename: lab4.cpp
            report:
                - Цель работы
                - Задание на лабораторную работу
                - Описание используемых алгоритмов замещения страниц
                - Результат выполнения работы
                - Исходный код программы с комментариями
                - Выводы
        "5":
            github-prefix: os-task5
            short-name: ЛР5
            taskid-max: 30
            penalty-max: 10
            # ignore-completion-date: True
            ci:
              workflows:
                - run-autograding-tests
                - cpplint
            files:
                - client.cpp
                - server.cpp
            moss:
                language: cc
                max-matches: 1000
                local-path: lab5
                additional:
                  - suai-os-2021
                  - suai-os-2022
                  - suai-os-2023
            report:
                - Цель работы
                - Задание на лабораторную работу
                - Схема взаимодействия между клиентом и сервером
                - Результат выполнения работы
                - Исходный код программы с комментариями
                - Выводы
        "6":
            github-prefix: os-task5
            short-name: ЛР6
            taskid-max: 30
            penalty-max: 7
            moss:
                language: cc
                max-matches: 1000
                local-path: lab5
                additional:
                  - suai-os-2021
                  - suai-os-2022
                  - suai-os-2023
            report:
                - Цель работы
                - Задание на лабораторную работу
                - Описание структуры конфигурационного файла
                - Содержимое написанного конфигурационного файла
                - Логи сборки проекта в облаке
                - Исходный код тестов
                - Выводы
misc:
    requests-timeout: 5
```
